import type { MetadataRoute } from 'next';

/**
 * The tenant app's home-screen install (`/t`), not the staff app's.
 *
 * `scope` and `start_url` are both `/t`: a tenant taps "เพิ่มลงในหน้าจอโฮม"
 * once and thereafter opens their bills from an icon with no browser bar,
 * while reception — a shared desktop machine — is out of scope and is never
 * offered an install. There is no native app to download and no store account
 * to keep; this is what makes the website behave like one.
 *
 * Icons are generated by `scripts/make-icons.py` (full-bleed, so iOS does not
 * render transparency as black and Android's maskable crop keeps the mark).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'อมาใหม่ เรสซิเดนซ์',
    short_name: 'อมาใหม่',
    description: 'ดูบิลค่าเช่า ค่าน้ำค่าไฟ และแจ้งชำระเงิน',
    lang: 'th',
    start_url: '/t',
    scope: '/t',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#FFFFFF',
    // Style A's --primary: the phone's status bar picks this up in standalone.
    theme_color: '#2563EB',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
