import { PrismaClient } from '@prisma/client';
import { env } from '../env.js';

// The client is generated by `npm run db:pull` (prisma db pull && prisma generate).
// Until that has been run once against a migrated database, importing this file
// throws with Prisma's "did you run prisma generate" message — that is expected.
export const prisma = new PrismaClient({
  log: env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
});
